script: grunt browsertest
before_script: 
- npm install -g grunt-cli browserstack-test
language: node_js
env: 
  global: 
  - secure: HzDQC47+AW8dnAeUh3pxBJxz7qbglGc9+fk415V55RmFChg2ukDf6vaa5zYYIp6MU21ModXkFjgl2aqfTAv8tdoSLsjFFsa9SDCUptMbsVzlucYFieKecjUuJ+QYWQ6SrI0vjqEhYxN/tm/NRMxi5oquRNZyOdZA0SS/9A124Qw=
  - secure: jL0i/WMbtA8AQKr6tbdiHvNJykFcKFrgWK0BVEatjjOzL3wEanC+/jBmy9L7Dx55XnQp1AWomqCdNqZNRz2cIpwU3433nmqZqF4CS5WiZOUuHYYbF2XLUuxkNC+W0TCP/mnI3lkSf5Yfnl/GYVT126xegMqpKcv4LS/auutjPiA=
  - secure: dUeFloFWeozRLcg6b5WfPY89PjZZEgw8HUF2eMBh9lekoHcH2CQaDrRNIbJ4aL6v+P8BsUBCoh9IARJ2OG8cC33GUxEpLoXsRCb7c7ElDuLLlr2xpSwngCg0JKNPQ1V9IZHxvEVhkzLgJkfHfmx20YhocbpL5OMrhdeh8ym9TFY=
node_js: 
- 0.1
